// Code generated by hertz generator.

package main

import (
	"hz_demo/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/index", handler.Index)
	r.GET("/register", handler.RegisterGet)
	r.GET("/docs", handler.DocList)
	r.GET("/postdoc", handler.NewDocGet)
	r.GET("/doc/:doc_id", handler.DocDetail)
	r.GET("/user/:user_id", handler.UserProfile)
	r.GET("/quit_login", handler.QuitLogin)

	r.POST("/login", handler.Login)
	r.POST("/register", handler.RegisterPost)
	r.POST("/postdoc", handler.NewDocPost)
}
